# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-17 02:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tomu', '0003_auto_20170417_0231'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Chatter',
        ),
    ]
