# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-17 16:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tomu', '0004_delete_chatter'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField()),
                ('name', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name_plural': 'Permissions',
                'verbose_name': 'Permission',
            },
        ),
    ]
