# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-17 17:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tomu', '0005_permission'),
    ]

    operations = [
        migrations.AddField(
            model_name='permission',
            name='bot',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='permission',
            name='calendar',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='permission',
            name='files',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='permission',
            name='lists',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='permission',
            name='polls',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='permission',
            name='users',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
