# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-17 18:04
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tomu', '0006_auto_20170417_1752'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chatter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discord_username', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name_plural': 'Chatters',
                'verbose_name': 'Chatter',
            },
        ),
        migrations.RemoveField(
            model_name='permission',
            name='level',
        ),
        migrations.AlterField(
            model_name='permission',
            name='bot',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='permission',
            name='calendar',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='permission',
            name='files',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='permission',
            name='lists',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='permission',
            name='polls',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='permission',
            name='users',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='chatter',
            name='permissions',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tomu.Permission'),
        ),
        migrations.AddField(
            model_name='chatter',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
