# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-11 21:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20170602_1325'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='idinPoll',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
